<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

define( 'WA_CONNECTOR_DEFAULTS', [
    'general' => [
        'wa_enable_connector' => 'no',
        'wa_template_api_url' => 'https://whatatalk-api.azguardstech.com/',
        'wa_auth_api_url'     => 'https://whatatalk-auth.azguardstech.com//realms/azguards-whatsapp/protocol/openid-connect/token',
        'wa_client_id'        => '',
        'wa_client_secret'    => '',
        'wa_grant_type'       => 'client_credentials',
        'wa_enable_order_created'      => 'yes',
        'wa_enable_order_invoice'      => 'yes',
        'wa_enable_order_shipment'     => 'yes',
        'wa_enable_order_cancellation' => 'yes',
        'wa_enable_order_credit_memo'  => 'yes',
        'wa_enable_abandoned_cart'     => 'yes',
    ],
    'cron' => [
        'wa_campaign_sync_schedule' => '1',
        'wa_contact_sync_schedule'  => '1',
        'wa_template_sync_schedule' => '60',
    ],
    'templates' => [
        'order_created' => [
            'event_code'    => 'order_created',
            'template_name' => 'order_created_one',
            'category'      => 'Utility',
            'language'      => 'en_US',
            'header_type'   => 'text',
            'header_text'   => 'Order Confirmed',
            'body_template' => "Hi {{var order.customer_firstname}}, your order #{{var order.increment_id}} has been placed successfully. Total: {{var order.grand_total}}.\n\nItems:\n{{#items}}{{var items.name}} x {{var items.qty_ordered}} = {{var items.row_total}}{{/items}} Thanks",
            'footer_template' => 'Thank you for your order!',
            'buttons_json'    => '[{"type":"URL","text":"View Order","button_url":"{{var store.base_url}}sales/order/view/order_id/{{var order.entity_id}}/"}]',
        ],
        'order_invoice' => [
            'event_code'    => 'order_invoice',
            'template_name' => 'order_invoice',
            'category'      => 'Utility',
            'language'      => 'en_US',
            'header_type'   => 'text',
            'header_text'   => 'Invoice for Order',
            'body_template' => 'Hi {{var order.customer_firstname}}, your invoice #{{var invoice.increment_id}} for order #{{var order.increment_id}} is now available. Amount Paid: {{var invoice.grand_total}}. Thanks',
            'footer_template' => 'View your account for details.',
            'buttons_json'    => '[{"type":"URL","text":"View Order","button_url":"{{var store.base_url}}sales/order/view/order_id/{{var order.entity_id}}/"}]',
        ],
        'order_shipment' => [
            'event_code'    => 'order_shipment',
            'template_name' => 'order_shipment',
            'category'      => 'Utility',
            'language'      => 'en_US',
            'header_type'   => 'text',
            'header_text'   => 'Your Order is Shipped!',
            'body_template' => "Hi {{var order.customer_firstname}}, your order #{{var order.increment_id}} is on its way!\n\nTracking: {{var shipment.tracking_number}}\nCarrier: {{var shipment.carrier_name}} Thanks",
            'footer_template' => 'Track your package for updates.',
            'buttons_json'    => '[{"type":"URL","text":"View Order","button_url":"{{var store.base_url}}sales/order/view/order_id/{{var order.entity_id}}/"}]',
        ],
        'order_cancellation' => [
            'event_code'    => 'order_cancellation',
            'template_name' => 'order_cancelled',
            'category'      => 'Utility',
            'language'      => 'en_US',
            'header_type'   => 'text',
            'header_text'   => 'Order Cancelled',
            'body_template' => 'Hi {{var order.customer_firstname}}, your order #{{var order.increment_id}} has been cancelled. Status: {{var order.status}}. Thanks',
            'footer_template' => 'Contact support for any questions.',
            'buttons_json'    => '[{"type":"URL","text":"View Order","button_url":"{{var store.base_url}}sales/order/view/order_id/{{var order.entity_id}}/"}]',
        ],
        'order_credit_memo' => [
            'event_code'    => 'order_credit_memo',
            'template_name' => 'order_refunded',
            'category'      => 'Utility',
            'language'      => 'en_US',
            'header_type'   => 'text',
            'header_text'   => 'Refund Processed',
            'body_template' => 'Hi {{var order.customer_firstname}}, a refund #{{var creditmemo.increment_id}} has been processed for your order #{{var order.increment_id}}. Refund Amount: {{var creditmemo.grand_total}}. Thanks',
            'footer_template' => 'Refunds usually take 5-7 days.',
            'buttons_json'    => '[{"type":"URL","text":"View Order","button_url":"{{var store.base_url}}sales/order/view/order_id/{{var order.entity_id}}/"}]',
        ],
        'abandon_cart' => [
            'event_code'    => 'abandon_cart',
            'template_name' => 'abandoned_cart',
            'category'      => 'Marketing',
            'language'      => 'en_US',
            'header_type'   => 'text',
            'header_text'   => 'Did you forget something?',
            'body_template' => "Hi {{var quote.customer_firstname}}, we noticed you left items in your cart. Your total is {{var quote.grand_total}}. Complete your purchase now!\n\nItems:\n{{#items}}{{var items.name}} x {{var items.qty}} = {{var items.row_total}}\n{{/items}} Thanks",
            'footer_template' => 'Expires soon!',
            'buttons_json'    => '[{"type":"URL","text":"View Cart","button_url":"{{var store.base_url}}checkout/cart/"}]',
        ],
    ],
    'widget' => [
        'wa_widget_enable'          => 'yes',
        'wa_widget_business_name'   => 'Chat with us',
        'wa_widget_welcome_message' => 'Hi! How can we help you?',
        'wa_widget_tooltip_text'    => 'Chat with us on WhatsApp!',
        'wa_widget_position'        => 'bottom-right',
        'wa_widget_primary_color'   => '#25D366',
        'wa_widget_show_tooltip'    => 'yes',
        'wa_widget_auto_open_delay' => '0',
    ],
]);
